// Generated by CoffeeScript 1.6.2
/*
  @author   Patrick Kromeyer
*/

var ICalendarEngine;

ICalendarEngine = require('../src/ICalendarEngine.js');

describe('ICalendarEngine', function() {
  return it('should create an icalendar string', function() {
    var parser, test;

    parser = function() {
      return [
        {
          name: 'testName',
          dateStart: new Date(Date.UTC(2013, 1 - 1, 5, 8, 30, 0, 0)),
          dateEnd: new Date(Date.UTC(2013, 1 - 1, 5, 9, 0, 0, 0)),
          description: 'testDescription'
        }
      ];
    };
    test = function(result) {
      expect(result).toMatch(/^BEGIN:VCALENDAR(.|\r\n)+END:VCALENDAR\r\n$/);
      expect(result).toMatch(/BEGIN:VEVENT(.|\r\n)+END:VEVENT/);
      expect(result).toMatch(/SUMMARY:testName/);
      expect(result).toMatch(/DTSTART:20130105T083000Z/);
      expect(result).toMatch(/DTEND:20130105T090000Z/);
      return expect(result).toMatch(/DESCRIPTION:testDescription/);
    };
    return runs(function() {
      var channelId, engine;

      engine = new ICalendarEngine(parser, test);
      channelId = engine.createChannel();
      return engine.closeChannel(channelId);
    });
  });
});
