// Generated by CoffeeScript 1.6.2
/*
  @author   Patrick Kromeyer
*/

var isNumber;

isNumber = require('../src/isNumber.js');

describe('isNumber', function() {
  it('should work with number', function() {
    return expect(isNumber(5.5)).toBeTruthy();
  });
  return it('should work with string', function() {
    expect(isNumber('5.5')).toBeTruthy();
    return expect(isNumber('x')).toBeFalsy();
  });
});

module.exports = isNumber;
