// Generated by CoffeeScript 1.6.2
/*
  @author   Patrick Kromeyer
*/

var Engine, ICalendarEngine, icalendar,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

icalendar = require('icalendar');

Engine = require('./Engine.js');

ICalendarEngine = (function(_super) {
  __extends(ICalendarEngine, _super);

  function ICalendarEngine(parser, callback) {
    ICalendarEngine.__super__.constructor.call(this, callback);
    this._parser = parser;
  }

  ICalendarEngine.prototype._handle = function() {
    var channelId, event, eventObject, events, ical, _i, _len;

    if (!this._isReady()) {
      return;
    }
    ical = new icalendar.iCalendar();
    for (channelId in this._channelContent) {
      events = this._parser(this._channelContent[channelId]);
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        event = events[_i];
        eventObject = new icalendar.VEvent(event.dateStart.toJSON());
        eventObject.setSummary(event.name);
        eventObject.setDate(event.dateStart, event.dateEnd);
        eventObject.setDescription(event.description);
        ical.addComponent(eventObject);
      }
    }
    return this._callback(ical.toString());
  };

  return ICalendarEngine;

})(Engine);

module.exports = ICalendarEngine;
