// Generated by CoffeeScript 1.6.2
/*
  @author   Patrick Kromeyer
*/

var cheerio, moment, semesterPlanParser;

cheerio = require('cheerio');

moment = require('moment');

semesterPlanParser = function(html) {
  var $, data, date, matches, url;

  data = [];
  $ = cheerio.load(html);
  url = $('[href^="javascript:void(printUrl"]').attr('href');
  matches = url.match(/date=(\d+)/);
  date = moment.unix(parseInt(matches[1]));
  $('[data-role=listview]').each(function(i, elem) {
    $(elem).find('li:not(:first-child)').each(function(j, e) {
      var dateEnd, dateStart, event, matchTime;

      dateStart = date.clone();
      dateEnd = date.clone();
      matchTime = $(e).find('.cal-time').text().match(/^(\d{2}):(\d{2})-(\d{2}):(\d{2})$/);
      dateStart.hours(matchTime[1]);
      dateStart.minutes(matchTime[2]);
      dateEnd.hours(matchTime[3]);
      dateEnd.minutes(matchTime[4]);
      event = {
        'name': $(e).find('.cal-title').text(),
        'dateStart': dateStart.toDate(),
        'dateEnd': dateEnd.toDate(),
        'description': $(e).find('.cal-res').text()
      };
      return data.push(event);
    });
    return date.add('day', 1);
  });
  return data;
};

module.exports = semesterPlanParser;
