// Generated by CoffeeScript 1.6.2
/*
  @author   Patrick Kromeyer
*/

var SimpleCache;

SimpleCache = (function() {
  function SimpleCache() {
    this._cache = {};
    this._expirationDates = {};
  }

  SimpleCache.prototype._checkLifetime = function() {
    var key, now;

    now = Date.now();
    for (key in this._expirationDates) {
      if (this._expirationDates[key] < now) {
        delete this._expirationDates[key];
        delete this._cache[key];
      }
    }
  };

  SimpleCache.prototype.setItem = function(key, data, lifetime) {
    if (lifetime == null) {
      lifetime = 3600;
    }
    this._cache[key] = data;
    this._expirationDates[key] = Date.now() + lifetime;
  };

  SimpleCache.prototype.hasItem = function(key) {
    this._checkLifetime();
    if (this._cache[key]) {
      return true;
    } else {
      return false;
    }
  };

  SimpleCache.prototype.getItem = function(key) {
    this._checkLifetime();
    if (this._cache[key]) {
      return this._cache[key];
    } else {
      return null;
    }
  };

  return SimpleCache;

})();

module.exports = SimpleCache;
